export const GET_CUSTOMERS_PENDING = 'GET_CUSTOMERS_PENDING';
export const GET_CUSTOMERS_FULFILLED = 'GET_CUSTOMERS_FULFILLED';
export const GET_CUSTOMERS_REJECTED = 'GET_CUSTOMERS_REJECTED';

export const GET_ROOMS_PENDING = 'GET_ROOMS_PENDING';
export const GET_ROOMS_FULFILLED = 'GET_ROOMS_FULFILLED';
export const GET_ROOMS_REJECTED = 'GET_ROOMS_REJECTED';
